//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edenrose.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int id { get; set; }
        public Nullable<int> key { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string ContentDetail { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoKeywords { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Picture { get; set; }
    }
}
